### ISSUE TITLE
local images

### ISSUE THREAD

**Issue by franfranfranfran** [JoshLeT/prj-rev-bwfs-dasmoto#3]
https://github.com/JoshLeT/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/Resources/style.css#L27

great job including the images with your project folder and linking to them throughout the html. make sure to do this for all image resources, including this background image.

also, as your projects grow larger and more complicated, it can be helpful to organize the files in the resources folder by type. you can create separate folder within resources for css, images, etc...

**Comment by JoshLeT** [comment]
Thank you for the tip. I will store my images in the a separate folder within resources in future 👍
