### ISSUE TITLE
inline styling

### ISSUE THREAD

**Issue by franfranfranfran** [JoshLeT/prj-rev-bwfs-dasmoto#4]
https://github.com/JoshLeT/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L23

make sure to keep all of your styling inside the css file. it can get confusing when you have styling in many different places. 
use a class or id to add this unique styling

**Comment by JoshLeT** [comment]
Thank you for the tip 👍
