### ISSUE TITLE
div vs span

### ISSUE THREAD

**Issue by franfranfranfran** [JoshLeT/prj-rev-bwfs-dasmoto#5]
https://github.com/JoshLeT/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L33

consider using a span element instead of div for the price section. spans are naturally inline display, which will allow it to remain in line with the rest of the paragraph text instead of bumping down to the next line

**Comment by JoshLeT** [comment]
This is very useful. I had forgotten that span was inline.
